interface InviteEmailProps {
  inviterName?: string;
  organizationName?: string;
  inviteLink?: string;
}

export function InviteEmail({
  inviterName = "A colleague",
  organizationName = "a workspace",
  inviteLink = "https://app.saasplatform.com/invite/token123",
}: InviteEmailProps) {
  return (
    <table style={styles.outerTable}>
      <tr>
        <td align="center">
          <table style={styles.container}>
            {/* Header */}
            <tr>
              <td style={styles.header}>
                <div style={styles.logoContainer}>
                  <span style={styles.logoIcon}>▲</span>
                  <span style={styles.logoText}>Antigravity SaaS</span>
                </div>
              </td>
            </tr>

            {/* Body */}
            <tr>
              <td style={styles.body}>
                <h1 style={styles.heading}>You have been invited!</h1>
                <p style={styles.text}>
                  <strong>{inviterName}</strong> has invited you to join their team in the <strong style={styles.highlight}>{organizationName}</strong> workspace on Antigravity.
                </p>

                {/* Invite Card Box */}
                <table style={styles.inviteCard}>
                  <tr>
                    <td>
                      <table style={styles.cardHeader}>
                        <tr>
                          <td style={styles.avatarCol}>
                            <div style={styles.avatar}>
                              {organizationName.slice(0, 1).toUpperCase()}
                            </div>
                          </td>
                          <td style={styles.orgInfoCol}>
                            <strong style={styles.orgName}>{organizationName}</strong>
                            <span style={styles.orgMeta}>Team Workspace</span>
                          </td>
                        </tr>
                      </table>
                      <p style={styles.cardDescription}>
                        Join this workspace to collaborate on AI generation sessions, share secure document folders, inspect analytics charts, and manage developers assets.
                      </p>
                    </td>
                  </tr>
                </table>

                {/* Divider */}
                <div style={styles.divider} />

                {/* CTA Button */}
                <table style={styles.buttonContainer}>
                  <tr>
                    <td align="center">
                      <a href={inviteLink} target="_blank" rel="noopener noreferrer" style={styles.button}>
                        Accept Invitation
                      </a>
                    </td>
                  </tr>
                </table>

                {/* Expiration Notice */}
                <table style={styles.warningCard}>
                  <tr>
                    <td style={styles.warningIconCol}>
                      <span>⚠️</span>
                    </td>
                    <td style={styles.warningTextCol}>
                      This invitation was sent directly to your email address and will expire automatically in <strong>7 days</strong>. If you did not expect this invitation, you can safely ignore this email.
                    </td>
                  </tr>
                </table>

                <p style={styles.signature}>
                  Best regards,<br />
                  <strong>The Antigravity Team</strong>
                </p>
              </td>
            </tr>

            {/* Footer */}
            <tr>
              <td style={styles.footer}>
                <p style={styles.footerText}>
                  This invitation was generated by {inviterName} for the {organizationName} workspace.<br />
                  © 2026 Antigravity Inc, 100 Pine Street, San Francisco, CA.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  );
}

const styles = {
  outerTable: {
    width: "100%",
    backgroundColor: "#09090b",
    margin: 0,
    padding: "40px 0",
  },
  container: {
    maxWidth: "580px",
    width: "100%",
    backgroundColor: "#0f0f11",
    border: "1px solid #27272a",
    borderRadius: "16px",
    borderCollapse: "collapse" as const,
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
  },
  header: {
    padding: "32px 40px 24px 40px",
    borderBottom: "1px solid #1f1f23",
  },
  logoContainer: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  logoIcon: {
    fontSize: "20px",
    color: "#6366f1",
    fontWeight: "bold",
  },
  logoText: {
    fontSize: "16px",
    fontWeight: "bold" as const,
    color: "#fafafa",
    letterSpacing: "-0.5px",
  },
  body: {
    padding: "40px 40px 32px 40px",
  },
  heading: {
    fontSize: "22px",
    fontWeight: "800" as const,
    color: "#fafafa",
    margin: "0 0 16px 0",
    letterSpacing: "-0.5px",
    lineHeight: "1.3",
  },
  text: {
    fontSize: "14px",
    color: "#a1a1aa",
    margin: "0 0 24px 0",
    lineHeight: "1.6",
  },
  highlight: {
    color: "#f4f4f5",
  },
  inviteCard: {
    width: "100%",
    backgroundColor: "#18181b",
    border: "1px solid #27272a",
    borderRadius: "14px",
    padding: "20px",
    margin: "24px 0",
    borderCollapse: "collapse" as const,
  },
  cardHeader: {
    width: "100%",
    borderCollapse: "collapse" as const,
  },
  avatarCol: {
    width: "48px",
    verticalAlign: "middle",
  },
  avatar: {
    width: "40px",
    height: "40px",
    lineHeight: "40px",
    backgroundColor: "#6366f1",
    borderRadius: "10px",
    color: "#ffffff",
    textAlign: "center" as const,
    fontWeight: "bold" as const,
    fontSize: "18px",
  },
  orgInfoCol: {
    paddingLeft: "12px",
    verticalAlign: "middle",
  },
  orgName: {
    fontSize: "14px",
    fontWeight: "bold" as const,
    color: "#f4f4f5",
    display: "block",
  },
  orgMeta: {
    fontSize: "11px",
    color: "#71717a",
  },
  cardDescription: {
    fontSize: "12px",
    color: "#a1a1aa",
    lineHeight: "1.6",
    margin: "14px 0 0 0",
  },
  divider: {
    height: "1px",
    backgroundColor: "#1f1f23",
    margin: "32px 0",
  },
  buttonContainer: {
    width: "100%",
    margin: "24px 0",
  },
  button: {
    display: "inline-block",
    backgroundColor: "#4f46e5",
    border: "1px solid #6366f1",
    borderRadius: "12px",
    color: "#ffffff",
    fontSize: "13px",
    fontWeight: "bold" as const,
    textDecoration: "none",
    padding: "12px 28px",
    textAlign: "center" as const,
  },
  warningCard: {
    width: "100%",
    backgroundColor: "#ef4444/[0.03]",
    border: "1px solid #ef4444/20",
    borderRadius: "12px",
    padding: "16px",
    margin: "24px 0",
    borderCollapse: "collapse" as const,
  },
  warningIconCol: {
    width: "28px",
    verticalAlign: "top",
    fontSize: "14px",
  },
  warningTextCol: {
    paddingLeft: "8px",
    fontSize: "11px",
    color: "#fca5a5",
    lineHeight: "1.5",
    verticalAlign: "top",
  },
  signature: {
    fontSize: "13px",
    color: "#a1a1aa",
    margin: "32px 0 0 0",
    lineHeight: "1.5",
  },
  footer: {
    padding: "32px 40px",
    backgroundColor: "#09090b",
    borderTop: "1px solid #1f1f23",
    borderBottomLeftRadius: "16px",
    borderBottomRightRadius: "16px",
  },
  footerText: {
    fontSize: "11px",
    color: "#52525b",
    lineHeight: "1.6",
    margin: 0,
  },
};

export default InviteEmail;
